### ISSUE TITLE
Comparison with more popular InfluxDB libraries

### ISSUE THREAD

**Issue by dandv** [vicanso/influxdb-nodejs#7]
Thanks for the new InfluxDB library. It would help to document the motivation for writing it, and how it compares with the more established Node.js libraries for InfluxDB:
- [influx](https://www.npmjs.com/package/influx) by @node-influx
- [influent](https://www.npmjs.com/package/influent) by @gobwas

**Comment by vicanso** [comment]
@dandv 
I will compare this project with the other two modules to find out the differences later.

**Comment by dandv** [comment]
@vicanso: Thank you. Did you take a look at at the other projects before starting this one, or maybe you just went ahead and developed it for your own projects' needs?

**Comment by vicanso** [comment]
@dandv I and sorry for reply you.  Yes I did look at the other projects before. I think those projects are not convenient.

**Comment by dandv** [comment]
@vicanso: can you elaborate how the other libraries, and especially [the official client](https://docs.influxdata.com/influxdb/v1.1/tools/api_client_libraries/#javascript-node-js), are not convenient?

**Comment by sveip** [comment]
Too me it looks like the official library and it's doc has improved allot.

https://node-influx.github.io/manual/tutorial.html

When this library was created out was not the case.

Just my 2 cents.

**Comment by vicanso** [comment]
@dandv Since `node-influx` uses `influx ql` to query data, I don't want to write `select * from http where time >= -2h and time <= -1h `. I prefer querying data in this way:

```js
client.query('http')
  .set({
    'start': '-2h',
    'end': '-1h',
  })
```

@sveip  I write the project in my spare time .  Honestly, I suggest you to choose the official library for commercial purpose.
I start this project just because I want to write something in my spare time. It's not perfect, even contains flaws, but it's mine.

**Comment by sveip** [comment]
Thanks for the advice,

I think I'll stick to yours, I really like it ☺️

**Comment by vicanso** [comment]
@dandv @sveip  

[API](http://vicanso.github.io/influxdb-nodejs/Client.html) was written.
